# Generated by Django 3.0.3 on 2020-03-11 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('nik', models.CharField(max_length=16)),
                ('nama', models.CharField(max_length=50)),
                ('telp', models.CharField(max_length=13)),
                ('last_login', models.DateField(auto_now_add=True, verbose_name='last login')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('laporan', models.TextField(max_length=1000)),
                ('foto', models.ImageField(upload_to='media')),
                ('status', models.CharField(choices=[('0', '0'), ('Proses', 'Proses'), ('Selesai', 'Selesai')], default='Proses', max_length=50)),
                ('pelapor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tanggapan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('tanggapan', models.TextField(max_length=1000)),
                ('pengaduan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Pengaduan')),
                ('petugas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
