# Generated by Django 3.0.3 on 2020-03-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200311_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nama',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
