# Generated by Django 3.0.3 on 2020-03-15 13:05

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200312_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
