# Generated by Django 3.0.3 on 2020-04-15 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200415_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pengaduan',
            options={'permissions': [('can_create_report', 'Bisa Membuat Laporan'), ('can_add_pengaduan', 'Bisa Membuat Pengaduan'), ('can_view_pengaduan', 'Bisa Melihat Pengaduan'), ('can_delete_pengaduan', 'Bisa Menghapus Pengaduan')]},
        ),
    ]
