# Generated by Django 3.0.3 on 2020-04-23 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200422_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_admin_page', 'Bisa Melihat Admin Page'), ('can_view_masyarakat_page', 'Bisa Melihat Melihat Masyarakat Page'), ('can_view_staff_page', 'Bisa Melihat Staff Page'), ('can_create_pengaduan', 'Bisa Mengadu'), ('can_create_tanggapan', 'Bisa Membuat Tanggapan ')]},
        ),
    ]
